EveryAnalytics/web-analytics-handbook

- LICENSE
라이센스 파일을 추가했습니다. RAP와 동일한 MIT입니다.
> LICENSE 추가 (MIT)

- .eslintignore
- .eslintrc.json
- package.json
- yarn.lock
react-analytics-provider에 있는 eslint 설정과 동일합니다. prettier 설정도 마찬가지 방식으로 따로 PR 생성할게용
#27
> eslint 세팅 

- .gitignore
- .vscode/settings.json
- src/components/HomepageFeatures.tsx
- src/components/WikiTable/WikiTable.tsx
- src/hooks/usePagination.ts
- src/pages/index.js
- src/pages/wiki/index.js
- src/theme/Footer/index.tsx
- src/theme/Root.js
- src/theme/mq.ts
- #51 에서 설정된 prettier 를 기존에 있는 코드 전체에 일괄 적용하였습니다.
- `.vscode/settings.json` 파일의 editor.formatOnSave 값을 true 로 변경하여 코드 저장시 prettier 스타일로 자동 포맷팅 되도록 하였습니다.
resolve #53
> 추가된 prettier 설정 코드 전체 일괄 적용

- wiki.json
wiki.json 파일 네이밍 컨벤션에 맞게 문자열 수정
README.md 파일에 wiki.json 네이밍 컨벤션도 함께 정리되면 좋을 것 같은데 어떻게 생각하시나요?
resolve [#46](https://github.com/EveryAnalytics/web-analytics-handbook/issues/46)
> docs: fix string in wiki.json

- wiki.json
- 유료 검색, 자연 검색, 기여 용어를 용어집에 추가하였습니다.
resolve #
fix #
> 유료 검색, 자연 검색, 기여 용어집 추가

- README.md
리드미에 용어 네이밍 규칙을 추가했습니다.
resolve #47
fix #
> Update README - 구성, 용어 네이밍규칙 추가

- blog/2021-08-22-ga-url-fragmentation-issue.md
- url fragmentation 관련 블로그를 작성합니다. 
resolve #66
> doc/66: ga-url-fragmentation issue 블로그 작성

- blog/2021-08-22-ga-url-fragmentation-issue.md
author_title 값이 비어있어 build error 가 생겨 수정하였습니다.
resolve #
fix #
> doc/66 비어있는 author_title 항목값 삭제

- .all-contributorsrc
- README.md
RAP에 있는 all-contributor 를 WAH도 추가했습니다!
> add all-contributor

- README.md
> Add title to README for Contributors

- wiki.json
1. 소스/매체의 용어 정의 추가
2. 용어사전 정리 및 어조 통일
#107
> [Feature/107] 용어사전 추가 (소스, 매체), 톤 정리

- wiki.json
동일집단, 신규방문자, 종료율, 페이지뷰, 순페이지뷰수 를 추가했습니다
resolve #113
fix #
> doc: 용어 몇개 추가

- CONTRIBUTING.md
WAH에 대한 Contributing 안내 문서를 작성했습니다.
[RAP 컨트리뷰팅 문서](https://github.com/EveryAnalytics/react-analytics-provider/blob/main/CONTRIBUTING.md)를 참고하였습니다. WAH에 맞게 더 수정되었으면 하는 부분 아낌없이 피드백 부탁드립니다!!!!!!
- WAH readme에 따라 개발환경에 npm 대신 yarn을 넣었는데, 혹시 npm과 관련된 환경설정도 언급되어야 한다면 수정하겠습니다!
resolve #87 
fix #
> Contributing.md 파일 생성

- docs/handbook/google-analytics-basics/google-ads.md
GA Google Ads 핸드북을 작성했습니다!
[미리 보기](https://user-images.githubusercontent.com/48555121/131224344-f711eed0-e8cd-44fa-89d6-87c65dd6cc22.png)
resolve #95
fix #
> docs: GA Google Ads 핸드북 작성

- docs/handbook/intro.md
핸드북의 Introduction을 작성했습니다.
[미리보기](https://user-images.githubusercontent.com/48555121/132092722-d3d39589-94b2-47b1-9e23-f44f117e9055.png)
**특이사항**
발대식 소개 자료를 참고해 '웹 분석 기초'라는 섹션이 추가된다고 가정하고 작업했습니다. 작성되어있는 문서들(추적해야할 데이터, A/B테스트, 퍼널 분석)을 옮겨 넣고 '필요성'을 추가 작성해주면 될 것 같습니다!
**참고한 자료들**
- [react-analytics-provider 발대식 자료](https://docs.google.com/presentation/d/1Lxxc8okJp4qUcR0MegZzymzOLXJEKGEoYsVY2UJXass/edit#slide=id.p1)
- [Typescript Handbook](https://www.typescriptlang.org/docs/handbook/intro.html)
- [Docusaurus Documentation - Introduction](https://docusaurus.io/docs/next)
더 추가할만한 내용 추천받습니다 ㅎㅎ
resolve #116 
fix #
> docs: add handbook intro

- docusaurus.config.js
- package.json
- yarn.lock
- 최근 문서 작성자 및 최근 문서 업데이트 날짜 보이도록 config 추가
- [x ] 모든 **변경점**들을 확인했으며 적절히 설명했습니다.
- [x ] 빌드가 정상적으로 수행됨을 확인했습니다. (`yarn build`)
> chore:최근 문서 작성자 및 최근 문서 업데이트 날짜 보이도록 config 추가 

- docusaurus.config.js
- https://docusaurus.io/ko/docs/api/plugins/@docusaurus/plugin-sitemap
- 위 관련 plugin config 추가
> chore:sitemap plugin 추가

- docs/handbook/google-analytics-basics/how-to-collect-data.md
- GA 데이터 수집 관련 글 작성 완성 (GA 고급 1.1 동영상 정리)
- 아래 영상을 기반으로 작성하였습니다.
- https://www.youtube.com/watch?v=lpMmIPWuKTk&t=12s&ab_channel=GoogleAnalytics 
resolve #
fix #
> docs:GA 데이터 수집 관련 글 작성 완성 (GA 고급 1.1 동영상 정리)

- docs/handbook/Google-Analytics/01-Settings/04-search-console.md
Add GA settings-population&interests / ads
resolve #147 
fix #
> docs:Add GA settings-search console

- wiki.json
- Handbook 내에 작성된 GA 가이드가 새로운 버전으로 업데이트 될 예정
- 기존 컨텐츠에서 용어 사전에 추가할 만한 내용들 추출하여 wiki.json에 정리
resolve #170
> docs: wiki data migration to wiki.json from GA Handbook Contents
